id = "perfect-dusk"
name = "Perfect Dusk"
version = "1.0.0"
schema_version = 1
authors = ["Bikossor"]
description = "Beautiful and accessible dark theme for your favorite code editor"
repository = "https://github.com/Bikossor/Perfect-Dusk"
